### ISSUE TITLE
Invalid package reference

### ISSUE THREAD

**Issue by mlemvigh-jabra** [salesforce/demo-scv-connector#13]
The SCV connector base has been updated to:
"@salesforce/scv-connector-base": "^3.5.1",

But the scv-connector-base in v 3.5.1 has been published without the namespace:
https://www.npmjs.com/package/scv-connector-base

npm install fails as a result.

**Comment by ssdey1** [comment]
I am also facing the same issue.

**Comment by estrudels** [comment]
https://github.com/mlemvigh-jabra && https://github.com/ssdey1

When I reached out to the **Salesforce Team** they said that we should be using the following **NPM Package**

* https://www.npmjs.com/package/@salesforce/scv-connector-base

The other SCV Connector Base (Non @Salesforce) NPM package was said to be not correct and not supposed to be visible

* https://www.npmjs.com/package/scv-connector-base

**Comment by estrudels** [comment]
@mlemvigh-jabra Could you please consider **Closing** this issue, as it has been resolved and now is currently using `3.5.4` from the package `@salesforce/scv-connector-base`

https://www.npmjs.com/package/@salesforce/scv-connector-base

Thanks
