### ISSUE TITLE
Unable to disable hold/unhold functionality for a THIRD_PARTY participant.

### ISSUE THREAD

**Issue by trustos** [salesforce/demo-scv-connector#5]
When using a HARD_PHONE and adding a participant to an existing conversation we are unable to disable the hold/unhold functionality for the added participant. By documentation we should be able to disable hold by passing holdEnabled: false to the callInfo. 

In the addParticipant method in the vendor-sdk in the returned result we pass as described: 
new ParticipantResult({
        phoneNumber: contact.phoneNumber,
        callInfo: new CallInfo({ isOnHold: false, holdEnabled: false }),
        initialCallHasEnded:
          parentCall.callAttributes &&
          parentCall.callAttributes.initialCallHasEnded,
        callId: newCall.callId
      })

but this is not working. We also tried to publish an event Constants.CALL_TYPE.ADD_PARTICIPANT in the addParticipant method with the ParticipantResult payload and the holdEnabled: false in the callInfo again without luck.

In addition we also tried to set holdEnabled to false in the connectParticipant when the Constants.EVENT_TYPE.PARTICIPANT_CONNECTED event is published again without being able to disable the hold functionality.

Could you give us an isight of how to do that or is it a bug?

**Comment by trustos** [comment]
This behaviour is due to the lack of support in the https://{salesforce-org}lightning.force.com/components/opencti/phoneCallControls.js.

```
this.updateTransferControls(),
this.transferCallState = i.STATES.CONNECTED,
t.callInfo && t.callInfo.isOnHold && (this.transferCallIsOnHold = !0, // Here only the isOnHold property is evaluated
this.updateTransferControls()),
```

Thus I am unable to control dynamically the call controls for adding participant.

**Comment by dlouvton** [comment]
Yes, this is not supported currently. You can pass the holdEnabled: false on CALL_STARTED or CALL_CONNECTED (for the parent call) and then when addParticipant the hold will be disabled.

**Comment by estrudels** [comment]
@trustos Would you consider **Close** this issue, as @dlouvton has communicated the current behavior, and given you a **workaround** for your case. Warm regards.
