### ISSUE TITLE
Getting Certificate Invalid Error

### ISSUE THREAD

**Issue by shubham1079** [salesforce/demo-scv-connector#7]
On running the npm start command and opening the local host url (https://127.0.0.1:8080/). I am getting below error.
<img width="1126" alt="Screenshot 2022-01-12 at 9 45 58 PM" src="https://user-images.githubusercontent.com/97528138/149179025-823b16e4-7beb-4aca-8f9b-0b5e1b89146d.png">

**Comment by dlouvton** [comment]
Yes, this is expected. If you want to avoid these certificate errors you will need to create your own certificate (cert.key and cert.pem) and put them on the ca folder.
Some browsers let you bypass these certificate errors.

**Comment by estrudels** [comment]
@shubham1079 Could you please consider **Close** this issue, as @dlouvton has confirmed this is expected behavior, and no further actions/works is required at this time. Warm regards.

**Comment by estrudels** [comment]
Bump @shubham1079

**Comment by shubham17007** [comment]
Hi @estrudels @dlouvton , thank you for the update on this. I have no further questions and this issue can be closed. For some reason i am not able to view the close issue button. May be @dlouvton can close this one.

**Comment by shubham1079** [comment]
Hi @dlouvton @estrudels thank you for update on this. I have no further questions, closing the issue.
