### ISSUE TITLE
Getting error "No env file present for the current environment:  undefined"

### ISSUE THREAD

**Issue by shubham17007** [salesforce/demo-scv-connector#9]
Getting below error on running **npm start**

_No env file present for the current environment: undefined_

How can we resolve this error ? 

![image](https://user-images.githubusercontent.com/102367008/160127934-86723dbf-f4f0-431c-b73f-563d5dbfbf8b.png)

**Comment by dlouvton** [comment]
You will need to populate the certificate files in the ca directory based on these instructions https://github.com/salesforce/demo-scv-connector#config-setup

**Comment by SzeMTan** [comment]
Does the instruction mean "Replace cert.key with server.key and replace cert.pem with server.crt"? 
This instruction is rather confusing - Add generated cert.key(server.key) and cert.pem(server.crt) in demo-connector/ca/

cert.pem and server.crt are not of the same type. 
Or am I supposed to replace the text inside the cert.key and cert.pem files?

**Comment by dlouvton** [comment]
Yes, replace the text, not the files.

**Comment by estrudels** [comment]
@shubham17007 As this is **working as expected** and @dlouvton has informed you on what you should do, could you please consider **Closing** this Issue. Thanks, warm regards.

**Comment by estrudels** [comment]
Bump @shubham17007

**Comment by estrudels** [comment]
Are on of you able to close this issue, as no further work/explanation required

@rjanamanchi-sfdc @paolo-botta-salesforce @rjanamanchi-sfdc

**Comment by shubham17007** [comment]
Hi @estrudels @dlouvton thank you for the update on this. No further action is required so I am closing this issue.
